Dropy/urls.py
from django.urls import path
from Dropy import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Dropy'
urlpatterns = [
    path('drop/<int:pk>', views.drop_details, name='drop_details'),
    path('all_drops', views.all_drops, name='all_drops'),
    path('add_drop', views.add_drop, name='add_drop'),
    path('update_drop/<int:pk>', views.update_drop, name='update_drop'),
    path('delete_drop/<int:pk>', views.delete_drop, name='delete_drop'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Forum/urls.py
from django.urls import path
from Forum import views

app_name = 'Forum'
urlpatterns = [
    path('all_topics', views.all_topics, name='all_topics'),
    path('topic/<int:pk>', views.topic_details, name='topic_details'),
    path('add_topic', views.add_topic, name='add_topic'),
    path('update_topic/<int:pk>', views.update_topic, name='update_topic'),
    path('delete_topic/<int:pk>', views.delete_topic, name='delete_topic'),
]

HW_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_site.urls')),
    path('members/', include('Użytkownicy.urls')),
    path('posts/', include('Posty.urls')),
    path('drops/', include('Dropy.urls')),
    path('forum/', include('Forum.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main_site/urls.py
from django.urls import path
from Main_site import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Main_site'
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posty/urls.py
from django.urls import path
from Posty import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Posty'
urlpatterns = [
    path('post/<int:pk>', views.post_details, name='post_details'),
    path('all_posts', views.all_posts, name='all_posts'),
    path('add_post', views.add_post, name='add_post'),
    path('update_post/<int:pk>', views.update_post, name='update_post'),
    path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Base_html/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>HW_Blog</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body class="d-flex flex-column min-vh-100" style="padding-top: 55px">
        {% include 'Base_html/navbar.html' %}
        {% block content %}
        {% endblock %}
        {% include 'Base_html/footer.html' %}
    </body>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</html>

templates/Base_html/footer.html
<footer class="footer mt-auto bg-dark py-3">
    <div class="container text-white text-center">
        <p class="mb-1">Copyright ©2023 Mateusz Szelągowski</p>
    </div>
</footer>

templates/Base_html/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md fixed-top" style="background-color: #fd7e14;">
          <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'Main_site:home' %}">HW_Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
              <div class="offcanvas-header text-dark" style="background-color: #fd7e14;">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close" style="background-color: white"></button>
              </div>
              <div class="offcanvas-body">
                <ul class="navbar-nav fw-semibold justify-content-end text-center flex-grow-1 column-gap-lg-2">
                    {% if user.is_authenticated %}
                        {% if user.profile.profile_pic %}
                            <li class="nav-item text-center">
                                <img class="img-fluid rounded-circle mt-1" src="{{ user.profile.profile_pic.url }}" style="height: 35px; width: 35px" alt="">
                            </li>    
                        {% else %}
                            <li class="nav-item text-center">
                                <img class="img-fluid rounded-circle mt-1" src="{% static 'images/blank-profile_pic.png' %}" style="height: 35px; width: 35px; " alt="">
                            </li>
                        {% endif %}    
                        <li class="nav-item text-center">
                            <a class="nav-link active" href="{% url 'user_profile' request.user.id %}">Witaj, {{ user.username }}</a>
                        </li>
                        <li class="border border-start border-black">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Posty:all_posts' %}">Posty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Dropy:all_drops' %}">Dropy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Forum:all_topics' %}">Forum</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Main_site:search' %}">Szukaj</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-light btn-outline-dark fw-semibold d-flex justify-content-center" href="{% url 'logout_user' %}" role="button" style="border-width: medium">
                                Wyloguj się
                                <img class="hstack ms-2" src="{% static 'bootstrap-icons-1.11.3/box-arrow-right.svg' %}" alt="Lock" width="23" height="23"> 
                            </a> 
                        </li> 
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Posty:all_posts' %}">Posty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Dropy:all_drops' %}">Dropy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Main_site:search' %}">Szukaj</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-light btn-outline-dark fw-semibold d-flex justify-content-center" href="{% url 'login_user' %}" role="button" style="border-width: medium">
                                Zaloguj się
                                <img class="hstack ms-1" src="{% static 'bootstrap-icons-1.11.3/person-fill-lock.svg' %}" alt="Lock" width="23" height="23"> 
                            </a> 
                        </li>
                    {% endif %}
                </ul>
              </div>
            </div>
          </div>
</nav>