Dropy/urls.py
from django.urls import path
from Dropy import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Dropy'
urlpatterns = [
    path('drop/<int:pk>', views.drop_details, name='drop_details'),
    path('all_drops', views.all_drops, name='all_drops'),
    path('add_drop', views.add_drop, name='add_drop'),
    path('update_drop/<int:pk>', views.update_drop, name='update_drop'),
    path('delete_drop/<int:pk>', views.delete_drop, name='delete_drop'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Forum/urls.py
from django.urls import path
from Forum import views

app_name = 'Forum'
urlpatterns = [
    path('all_topics', views.all_topics, name='all_topics'),
    path('topic/<int:pk>', views.topic_details, name='topic_details'),
    path('add_topic', views.add_topic, name='add_topic'),
    path('update_topic/<int:pk>', views.update_topic, name='update_topic'),
    path('delete_topic/<int:pk>', views.delete_topic, name='delete_topic'),
]

HW_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_site.urls')),
    path('members/', include('Użytkownicy.urls')),
    path('posts/', include('Posty.urls')),
    path('drops/', include('Dropy.urls')),
    path('forum/', include('Forum.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main_site/urls.py
from django.urls import path
from Main_site import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Main_site'
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posty/urls.py
from django.urls import path
from Posty import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Posty'
urlpatterns = [
    path('post/<int:pk>', views.post_details, name='post_details'),
    path('all_posts', views.all_posts, name='all_posts'),
    path('add_post', views.add_post, name='add_post'),
    path('update_post/<int:pk>', views.update_post, name='update_post'),
    path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Main_page/main.html
{% extends 'Base_html/base.html' %}
{% load static %}
{% block content %}
    {% for msg in messages %}
     <div class="container-fluid mt-3">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ msg }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
     </div>
    {% endfor %}
     <div class="container-fluid ms-3 me-3 mb-2 pt-3" style="height: auto; width: auto">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'images/IMG_E0778.JPG' %}" class="object-fit-cover" alt="..." style="height: 135px; width: 1700px">
            </div>
            <div class="carousel-item">
              <img src="{% static 'images/IMG_0782.JPG' %}" class="object-fit-cover" alt="..." style="height: 135px; width: 1700px">
            </div>
            <div class="carousel-item">
              <img src="{% static 'images/IMG_0780.JPG' %}" class="object-fit-cover" alt="..." style="height: 135px; width: 1700px">
            </div> 
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
     </div>
     <div class="container-fluid">
        <div class="row align-items-start ms-2 me-2 mt-2">
            <div class="col-md-4">
                <div class="card mb-3">
                    {% if user.is_authenticated and user.is_staff %}
                    <div class="card-header d-grid">
                        <a class="btn btn-primary" href="{% url 'Dropy:add_drop' %}" role="button">
                        Dodaj drop
                        </a>
                    </div>
                    {% endif %}
                    <div class="card-body row row-cols-1 pb-0">
                        {% for drop in Drops %}
                            <div class="col">
                                <div class="card mb-3">
                                    <div class="card-header">
                                        <p class="card-text fw-bold">{{ drop.Dni_do }}</p>
                                    </div>
                                    <div class="card-body">
                                        <div class="row hstack">
                                            <div class="col-3 ms-1">
                                                {% if drop.Zdjęcia %}
                                                    <img class="rounded" src="{{ drop.Zdjęcia.url }}" alt="..." style="height: 100px; width: 100px">
                                                {% else %}
                                                    <img class="img mt-2 rounded" src="{% static 'images/blank-drop-picture.png' %}" style="height: 90px; width: 90px" alt="">
                                                {% endif %}
                                            </div>   
                                            <div class="col-7 col-md-6 ms-5">
                                                <h5 class="card-title text-truncate"><a href="{% url 'Dropy:drop_details' drop.pk %}">{{ drop.Tytuł }}</a></h5>
                                                <p class="card-text fw-semibold">{{ drop.Typ }}<br>
                                                {{ drop.Data }} | Godzina: {{ drop.Godzina }}</p>
                                            </div>    
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>    
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    {% if user.is_authenticated and user.is_staff %}
                    <div class="card-header d-grid">
                        <a class="btn btn-primary" href="{% url 'Posty:add_post' %}" role="button">
                        Dodaj post
                        </a>
                    </div>
                    {% endif %}
                    <div class="card-body hstack row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 g-3">
                        {% for post in Posts %}
                            <div class="col">
                                <div class="card">
                                    {% if post.Zdjęcia %}
                                        <img class="img rounded" src="{{ post.Zdjęcia.url }}" alt="">
                                    {% else %}
                                        <img class="img rounded" src="{% static 'images/blank-drop-picture.png' %}" alt="">
                                    {% endif %}
                                    <div class="card-body">
                                        <h5 class="card-title text-truncate"><a href="{% url 'Posty:post_details' post.pk %}">{{ post.Tytuł }}</a></h5>
                                        {{ post.Kategoria }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div> 
            </div>
        </div>
     </div>
{% endblock %}

templates/Main_page/search.html
{% extends 'Base_html/base.html' %}
{% load static %}
{% block content %}
    {% for msg in messages %}
     <div class="container-fluid mt-3">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ msg }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
     </div>
    {% endfor %}
    <div class="container-fluid mt-3 mb-3">
         <div class="col">
            <div class="card">
                <div class="card-header d-grid justify-content-center">
                    <h2 class="fw-semibold">Wyszukaj na stronie</h2>
                    <form method="POST" action="{% url 'Main_site:search' %}">
                        {% csrf_token %}
                        <label for="exampleInputText" class="form-label"></label>
                        <input type="text" class="form-control" name="searched" id="exampleInputText">
                        <div class="d-flex justify-content-center"> 
                            <button type="submit" class="btn btn-sm fw-semibold mt-2" style="background-color: #fd7e14">Szukaj</button>  
                        </div>    
                    </form><br>
                </div>    
                <div class="card-body">
                    {% if posts %}
                        {% for post in posts %}
                            <div class="col">
                                <div class="card mb-3">
                                  <div class="card-body">
                                    <h6 class="fw-bold">POST</h6>  
                                    <h5 class="card-title text-truncate"><a href="{% url 'Posty:post_details' post.pk %}">{{ post.Tytuł }}</a> | {{ post.Kategoria }}</h5>
                                    <p class="card-text text-truncate">{{ post.Opis }}</p>
                                  </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% if user.is_authenticated %}
                        {% if topics %}
                            {% for topic in topics %}
                                <div class="col">
                                    <div class="card mb-3">
                                      <div class="card-body">
                                        <h6 class="fw-bold">FORUM</h6>
                                        <h5 class="card-title">
                                            <a href="{% url 'Forum:topic_details' topic.pk %}">
                                            {% if topic.Status_id == 1 %}
                                              <img src="{% static 'bootstrap-icons-1.11.3/unlock-fill.svg' %}" alt="Lock" width="20" height="15">
                                            {% else %}
                                              <img src="{% static 'bootstrap-icons-1.11.3/lock-fill.svg' %}" alt="Lock" width="20" height="15">
                                            {% endif %}    
                                            {{ topic.Tytuł }}</a> | {{ topic.Kategoria }}</h5>
                                        <p class="card-text text-truncate">{{ topic.Opis }}</p>
                                      </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                    {% if drops %}
                        <div class="card-body hstack row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-6 g-3">
                        {% for drop in drops %}
                            <div class="col">
                                <div class="card">
                                    {% if drop.Zdjęcia %}
                                        <img class="img rounded" src="{{ drop.Zdjęcia.url }}" alt="">
                                    {% else %}
                                        <img class="img rounded" src="{% static 'images/blank-drop-picture.png' %}" alt="">
                                    {% endif %}
                                    <div class="card-body">
                                        <h6 class="fw-bold">DROP</h6>
                                        <h5 class="card-title text-truncate"><a href="{% url 'Dropy:drop_details' drop.pk %}">{{ drop.Tytuł }}</a></h5>
                                        {{ drop.Typ }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div> 
         </div>
    </div>
{% endblock %}