Dropy/urls.py
from django.urls import path
from Dropy import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Dropy'
urlpatterns = [
    path('drop/<int:pk>', views.drop_details, name='drop_details'),
    path('all_drops', views.all_drops, name='all_drops'),
    path('add_drop', views.add_drop, name='add_drop'),
    path('update_drop/<int:pk>', views.update_drop, name='update_drop'),
    path('delete_drop/<int:pk>', views.delete_drop, name='delete_drop'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HW_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_site.urls')),
    path('members/', include('Użytkownicy.urls')),
    path('posts/', include('Posty.urls')),
    path('drops/', include('Dropy.urls')),
    path('forum/', include('Forum.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posty/urls.py
from django.urls import path
from Posty import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Posty'
urlpatterns = [
    path('post/<int:pk>', views.post_details, name='post_details'),
    path('all_posts', views.all_posts, name='all_posts'),
    path('add_post', views.add_post, name='add_post'),
    path('update_post/<int:pk>', views.update_post, name='update_post'),
    path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Post/add_post.html
{% extends 'Base_html/base.html' %}
{% block content %}
    {% if user.is_authenticated and user.is_staff %}
     <div class="d-flex justify-content-center mb-4" style="margin-top: 30px">
        <div class="card me-4 ms-4 shadow" style="width: 400px">
            <div class="card-header text-center">
                DODAJ NOWY POST
            </div>    
            <div class="card-body pb-0">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Tytuł</label>
                        {{ form.Tytuł }}
                        </div>
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Kategoria</label>
                        {{ form.Kategoria }}
                        </div>
                        <div class="mb-0">
                        <label for="exampleInputText" class="form-label mb-0">Opis</label>
                        {{ form.Opis }}
                        </div>
                        <div class="card-body">
                            <label for="exampleTextArea" class="form-label mb-1">Grafika posta</label>
                            <div class="card-body border text-truncate rounded" style="border: #0dcaf0">
                                {{ form.Zdjęcia }}
                            </div>    
                        </div>
                    <div class="d-flex justify-content-center">
                        <input class="btn btn-sm fw-semibold d-flex justify-content-center mt-0 mb-2" type="submit" value="Dodaj post" style="background-color: #fd7e14">
                    </div>   
                </form>
            </div>
        </div>
     </div>
    {% else %}
        <div class="d-flex justify-content-center" style="margin-top: 200px">
            <div class="card me-4 ms-4 shadow" style="width: 400px">
                <div class="card-header text-center">
                    BRAK DOSTĘPU
                </div>    
                <div class="card-body pt-3 pb-3 pb-0 text-center">
                    <p>Tylko administratorzy i moderatorzy strony mogą dodawać posty.</p>
                    <a href="{% url 'Posty:all_posts' %}">Przejdź do listy postów</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/Post/all_posts.html
 {% extends 'Base_html/base.html' %}
{% load static %}
{% block content %}
    {% for msg in messages %}
     <div class="container-fluid mt-3">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ msg }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
     </div>
    {% endfor %}
    <div class="container-fluid mt-3 mb-3">
         <div class="col">
            <div class="card">
                {% if user.is_authenticated and user.is_staff %}
                    <div class="card-header d-grid">
                        <a class="btn btn-primary" href="{% url 'Posty:add_post' %}" role="button" >
                        Dodaj post
                        </a>
                    </div>
                {% endif %}
                <div class="card-body hstack row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-6 g-3">
                    {% for post in posts %}
                        <div class="col">
                            <div class="card">
                                {% if post.Zdjęcia %}
                                    <img class="img rounded" src="{{ post.Zdjęcia.url }}" alt="">
                                {% else %}
                                    <img class="img rounded" src="{% static 'images/blank-drop-picture.png' %}" alt="">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title text-truncate"><a href="{% url 'Posty:post_details' post.pk %}">{{ post.Tytuł }}</a></h5>
                                    {{ post.Kategoria }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div> 
         </div><br>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Poprzednia</a></li>    
            {% endif %}
            <li class="page-item"><a class="page-link">Strona {{ posts.number }} z {{ posts.paginator.num_pages }}</a></li>
            {% if posts.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Następna</a></li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
            {% endif %}  
          </ul>
        </nav>
    </div>
{% endblock %}

templates/Post/post_details.html
{% extends 'Base_html/base.html' %}
{% load static %}
{% block content %}
    {% for msg in messages %}
     <div class="container-fluid mt-3">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ msg }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
     </div>
    {% endfor %}
    {% if post %}
         <div class="card mt-4 ms-4 me-4">
            <div class="card-header">
                <h1>{{ post.Tytuł }} - {{ post.Kategoria }}</h1>
            </div>    
            <div class="card-body">
                <div class="row">
                    {% if post.Zdjęcia %}
                    <div class="col text-start">
                          <img class="img rounded" src="{{ post.Zdjęcia.url }}" style="height: 200px; width: 200px" alt="">
                    </div>
                    <div class="col-10 mt-2 fw-semibold">
                        {{ post.Opis }}
                    </div>
                    {% else %}
                    <div class="col-12 fw-semibold">
                        {{ post.Opis }}
                    </div>    
                    {% endif %}
                </div>
            </div>   
            <div class="card-footer">
                {% if user.is_authenticated and user.is_staff %}
                    <div class="container-fluid text-center">
                        <div class="row justify-content-center">
                            <div class="col-4 d-grid">
                                <a class="btn btn-warning" href="{% url 'Posty:update_post' post.pk %}" role="button">
                                    Edytuj post
                                </a>
                            </div>
                            <div class="col-4 d-grid hstack">
                                <a role="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    Usuń post
                                </a>
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                      <div class="modal-content">
                                        <div class="modal-header bg-dark">
                                          <h1 class="modal-title text-white fs-5" id="exampleModalLabel">Usuń post</h1>
                                          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body text-center">
                                           Czy na pewno chcesz usunąć wybrany post?<br><br>
                                           <p class="fw-semibold">{{ post.Tytuł }} - {{ post.Kategoria }}</p>
                                        </div>
                                        <div class="modal-footer justify-content-center">
                                          <button type="button" class="btn btn-success" data-bs-dismiss="modal">Wróć</button>
                                          <a href="{% url 'Posty:delete_post' post.pk %}" type="button"  class="btn btn-danger">Usuń post</a>
                                        </div>
                                      </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
         </div>
    {% endif %}
{% endblock %}

templates/Post/update_post.html
{% extends 'Base_html/base.html' %}
{% block content %}
    {% if user.is_authenticated and user.is_staff %}
     <div class="d-flex justify-content-center mb-4" style="margin-top: 30px">
        <div class="card me-4 ms-4 shadow" style="width: 400px">
            <div class="card-header text-center">
                EDYCJA POSTA
            </div>    
            <div class="card-body pb-0">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Tytuł</label>
                            {{ form.Tytuł }}
                            </div>
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Kategoria</label>
                            {{ form.Kategoria }}
                            </div>
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Opis</label>
                            {{ form.Opis }}
                            </div>
                            <div class="card-body">
                                <label for="exampleTextArea" class="form-label mb-1">Grafika posta</label>
                                <div class="card-body border rounded" style="border: #0dcaf0">
                                    {{ form.Zdjęcia }}
                                </div>    
                            </div>
                        <div class="d-flex justify-content-center">
                        <input class="btn btn-sm fw-semibold d-flex justify-content-center mt-0 mb-2" type="submit" value="Zakończ edycję posta" style="background-color: #fd7e14">
                        </div>
                </form>
            </div>
        </div>
     </div>
    {% else %}
        <div class="d-flex justify-content-center" style="margin-top: 200px">
            <div class="card me-4 ms-4 shadow" style="width: 400px">
                <div class="card-header text-center">
                    BRAK DOSTĘPU
                </div>    
                <div class="card-body pt-3 pb-3 pb-0 text-center">
                    <p>Tylko administratorzy i moderatorzy strony mogą edytować posty.</p>
                    <a href="{% url 'Posty:all_posts' %}">Przejdź do listy postów</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}