Dropy/urls.py
from django.urls import path
from Dropy import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Dropy'
urlpatterns = [
    path('drop/<int:pk>', views.drop_details, name='drop_details'),
    path('all_drops', views.all_drops, name='all_drops'),
    path('add_drop', views.add_drop, name='add_drop'),
    path('update_drop/<int:pk>', views.update_drop, name='update_drop'),
    path('delete_drop/<int:pk>', views.delete_drop, name='delete_drop'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HW_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_site.urls')),
    path('members/', include('Użytkownicy.urls')),
    path('posts/', include('Posty.urls')),
    path('drops/', include('Dropy.urls')),
    path('forum/', include('Forum.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Drop/add_drop.html
{% extends 'Base_html/base.html' %}
{% block content %}
    {% if user.is_authenticated and user.is_staff%}
     <div class="d-flex justify-content-center mb-4" style="margin-top: 40px">
        <div class="card me-4 ms-4 shadow" style="width: 400px">
            <div class="card-header text-center">
                DODAJ NOWY DROP
            </div>    
            <div class="card-body pb-0">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Tytuł</label>
                        {{ form.Tytuł }}
                        </div>
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Typ</label>
                        {{ form.Typ }}
                        </div>
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Strona</label>
                        {{ form.Strona }}
                        </div>
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Cena</label>
                            <div class="input-group">
                                {{ form.Cena }}
                                <div class="input-group-text">zł</div>
                            </div>    
                        </div>
                        <div class="mb-2">
                        <label for="exampleInputText" class="form-label mb-0">Data (Dzień.Miesiąc.Rok)</label>
                        {{ form.Data }}
                        </div>
                        <div class="mb-0">
                        <label for="exampleInputText" class="form-label mb-0">Godzina (Godzina:Minuty)</label>
                        {{ form.Godzina }}
                        </div>
                        <div class="card-body">
                            <label for="exampleTextArea" class="form-label mb-1">Grafika dropu</label>
                            <div class="card-body border text-truncate rounded" style="border: #0dcaf0">
                                {{ form.Zdjęcia }}
                            </div>    
                        </div>
                    <div class="d-flex justify-content-center">
                        <input class="btn btn-sm fw-semibold d-flex justify-content-center mt-0 mb-2" type="submit" value="Dodaj drop" style="background-color: #fd7e14">
                    </div>  
                </form>
            </div>
        </div>
     </div>
    {% else %}
        <div class="d-flex justify-content-center" style="margin-top: 200px">
            <div class="card me-4 ms-4 shadow" style="width: 400px">
                <div class="card-header text-center">
                    BRAK DOSTĘPU
                </div>    
                <div class="card-body pt-3 pb-3 pb-0 text-center">
                    <p>Tylko administratorzy i moderatorzy strony mogą dodawać dropy.</p>
                    <a href="{% url 'Dropy:all_drops' %}">Przejdź do listy dropów</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/Drop/all_drops.html
{% extends 'Base_html/base.html' %}
{% load static %}
{% block content %}
    {% for msg in messages %}
     <div class="container-fluid mt-3">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ msg }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
     </div>
    {% endfor %}
    <div class="container-fluid mt-3 mb-3">
         <div class="col">
            <div class="card">
                {% if user.is_authenticated and user.is_staff %}
                    <div class="card-header d-grid">
                        <a class="btn btn-primary" href="{% url 'Dropy:add_drop' %}" role="button">
                        Dodaj drop
                        </a>
                    </div>
                {% endif %}
                <div class="card-body hstack row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-lg-6 g-3">
                    {% for drop in drops %}
                        <div class="col">
                            <div class="card">
                                {% if drop.Zdjęcia %}
                                    <img class="img rounded" src="{{ drop.Zdjęcia.url }}" alt="">
                                {% else %}
                                    <img class="img rounded" src="{% static 'images/blank-drop-picture.png' %}" alt="">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title text-truncate"><a href="{% url 'Dropy:drop_details' drop.pk %}">{{ drop.Tytuł }}</a></h5>
                                    {{ drop.Typ }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div> 
         </div><br>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if drops.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                <li class="page-item"><a class="page-link" href="?page={{ drops.previous_page_number }}">Poprzednia</a></li>    
            {% endif %}
            <li class="page-item"><a class="page-link">Strona {{ drops.number }} z {{ drops.paginator.num_pages }}</a></li>
            {% if drops.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ drops.next_page_number }}">Następna</a></li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ drops.paginator.num_pages }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
            {% endif %}  
          </ul>
        </nav>
    </div>
{% endblock %}

templates/Drop/drop_details.html
{% extends 'Base_html/base.html' %}
{% load static %}
{% block content %}
    {% for msg in messages %}
     <div class="container-fluid mt-3">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ msg }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
     </div>
    {% endfor %}
    {% if drop %}
         <div class="card mt-4 ms-4 me-4">
            <div class="card-header">
                <h1>{{ drop.Tytuł }} - {{ drop.Typ }}</h1>
            </div>
            <div class="card-body">
                    <div class="row">
                        <div class="col text-start">
                            {% if drop.Zdjęcia %}
                                <img class="img mt-2 rounded" src="{{ drop.Zdjęcia.url }}" style="height: 200px; width: 200px" alt="">
                            {% else %}
                                <img class="img mt-2 rounded" src="{% static 'images/blank-drop-picture.png' %}" style="height: 200px; width: 200px" alt="">
                            {% endif %}
                        </div>
                        <div class="col-10 mt-2 fw-semibold">
                            <h5 class="fw-bold">{{ drop.Dni_do }}</h5>
                            Strona: <a href="{{ drop.Strona }}">{{ drop.Strona }}</a><br>
                            Cena: {{ drop.Cena }} zł<br>
                            Data dropu: {{ drop.Data }}<br>
                            Godzina dropu: {{ drop.Godzina }}
                        </div>
                    </div>
            </div>
            <div class="card-footer">
                {% if user.is_authenticated and user.is_staff %}
                    <div class="container-fluid text-center">
                        <div class="row justify-content-center">
                            <div class="col-4 d-grid">
                                 <a class="btn btn-warning" href="{% url 'Dropy:update_drop' drop.pk %}" role="button">
                                 Edytuj drop
                                 </a>
                            </div>
                            <div class="col-4 d-grid hstack">
                                 <a role="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                 Usuń drop
                                 </a>
                                 <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                   <div class="modal-dialog">
                                     <div class="modal-content">
                                       <div class="modal-header bg-dark">
                                         <h1 class="modal-title text-white fs-5" id="exampleModalLabel">Usuń drop</h1>
                                         <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                                       </div>
                                       <div class="modal-body text-center">
                                         Czy na pewno chcesz usunąć wybrany drop?<br><br>
                                           <p class="fw-semibold">{{ drop.Tytuł }} - {{ drop.Typ }}</p>
                                       </div>
                                       <div class="modal-footer justify-content-center">
                                         <button type="button" class="btn btn-success" data-bs-dismiss="modal">Wróć</button>
                                         <a href="{% url 'Dropy:delete_drop' drop.pk %}" type="button"  class="btn btn-danger">Usuń drop</a>
                                       </div>
                                     </div>
                                   </div>
                                 </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>    
         </div>
    {% endif %}
{% endblock %}

templates/Drop/update_drop.html
{% extends 'Base_html/base.html' %}
{% block content %}
    {% if user.is_authenticated and user.is_staff %}
     <div class="d-flex justify-content-center mb-4" style="margin-top: 40px">   
         <div class="card me-4 ms-4 shadow" style="width: 400px">
                <div class="card-header text-center">
                    EDYCJA DROPU
                </div>    
                <div class="card-body pb-0">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Tytuł</label>
                            {{ form.Tytuł }}
                            </div>
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Typ</label>
                            {{ form.Typ }}
                            </div>
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Strona</label>
                            {{ form.Strona }}
                            </div>
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Cena</label>
                                <div class="input-group">
                                    {{ form.Cena }}
                                    <div class="input-group-text">zł</div>
                                </div>    
                            </div>
                            <div class="mb-2">
                            <label for="exampleInputText" class="form-label mb-0">Data (Dzień.Miesiąc.Rok)</label>
                            {{ form.Data }}
                            </div>
                            <div class="mb-0">
                            <label for="exampleInputText" class="form-label mb-0">Godzina (Godzina.Minuty)</label>
                            {{ form.Godzina }}
                            </div>
                            <div class="card-body">
                            <label for="exampleTextArea" class="form-label mb-1">Grafika dropu</label>
                                <div class="card-body border rounded" style="border: #0dcaf0">
                                {{ form.Zdjęcia }}
                                </div>    
                            </div>
                        <div class="d-flex justify-content-center">
                        <input class="btn btn-sm fw-semibold d-flex justify-content-center mt-0 mb-2" type="submit" value="Zakończ edycję dropu" style="background-color: #fd7e14">
                        </div>  
                    </form>
                </div>
         </div>
     </div>   
    {% else %}
        <div class="d-flex justify-content-center" style="margin-top: 200px">
            <div class="card me-4 ms-4 shadow" style="width: 400px">
                <div class="card-header text-center">
                    BRAK DOSTĘPU
                </div>    
                <div class="card-body pt-3 pb-3 pb-0 text-center">
                    <p>Tylko administratorzy i moderatorzy strony mogą edytować dropy.</p>
                    <a href="{% url 'Dropy:all_drops' %}">Przejdź do listy dropów</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}